import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.111.0/+esm';
import { CONFIG } from './config.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const isConfigured=()=>CONFIG.SUPABASE_URL&&!CONFIG.SUPABASE_URL.includes('SEU-PROJETO')&&CONFIG.SUPABASE_PUBLISHABLE_KEY&&!CONFIG.SUPABASE_PUBLISHABLE_KEY.includes('SUA_CHAVE');
let supabase=null, session=null, user=null, membership=null, company=null, employees=[], entries=[], members=[];

const ui={
  setup:$('#setupView'),auth:$('#authView'),onboarding:$('#onboardingView'),app:$('#appView'),modalBg:$('#modalBackdrop'),modal:$('#modal'),toast:$('#toast')
};
function showOnly(view){[ui.setup,ui.auth,ui.onboarding,ui.app].forEach(v=>v.classList.add('hidden'));view.classList.remove('hidden')}
function toast(message,type='success'){ui.toast.textContent=message;ui.toast.className=`toast ${type}`;setTimeout(()=>ui.toast.classList.add('hidden'),3500)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]))}
function initials(name=''){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'BH'}
function fmt(min=0){const n=Number(min)||0, sign=n>0?'+':n<0?'-':'', a=Math.abs(n);return `${sign}${Math.floor(a/60)}h ${String(a%60).padStart(2,'0')}m`}
function bclass(n){return n>0?'good':n<0?'bad':'zero'}
function canManageEmployees(){return ['owner','admin'].includes(membership?.role)}
function canManageTime(){return ['owner','admin','operator'].includes(membership?.role)}
function canManageCompany(){return ['owner','admin'].includes(membership?.role)}
function roleLabel(role){return ({owner:'Proprietário',admin:'Administrador',operator:'Responsável'})[role]||role}
function setBusy(btn,busy,text='Processando...'){if(!btn)return; if(busy){btn.dataset.old=btn.textContent;btn.disabled=true;btn.textContent=text}else{btn.disabled=false;btn.textContent=btn.dataset.old||btn.textContent}}
function openModal(html){ui.modal.innerHTML=html;ui.modalBg.classList.remove('hidden')}
function closeModal(){ui.modalBg.classList.add('hidden')}
window.closeModal=closeModal;
ui.modalBg.addEventListener('click',e=>{if(e.target===ui.modalBg)closeModal()});

if(!isConfigured()){showOnly(ui.setup)}else{boot()}
async function boot(){
  supabase=createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  supabase.auth.onAuthStateChange((event,newSession)=>{
    session=newSession;user=newSession?.user||null;
    if(event==='PASSWORD_RECOVERY'){openRecoveryModal();return}
    if(!user){clearState();showOnly(ui.auth);return}
    setTimeout(()=>routeAfterAuth(),0);
  });
  const {data}=await supabase.auth.getSession(); session=data.session; user=session?.user||null;
  if(user)await routeAfterAuth();else showOnly(ui.auth);
}
function clearState(){membership=null;company=null;employees=[];entries=[];members=[]}
async function routeAfterAuth(){
  try{
    const {data:memberRows,error}=await supabase.from('company_members').select('id,company_id,user_id,role,full_name,active,companies(id,name,cnpj,phone,address,logo_path,owner_user_id)').eq('user_id',user.id).eq('active',true).limit(1);
    if(error)throw error;
    if(!memberRows?.length){showOnly(ui.onboarding);return}
    membership=memberRows[0];company=membership.companies;showOnly(ui.app);applyIdentity();await loadAll();
  }catch(e){console.error(e);toast(e.message||'Erro ao carregar sua empresa.','error')}
}

$$('.auth-tab').forEach(btn=>btn.onclick=()=>{$$('.auth-tab').forEach(x=>x.classList.toggle('active',x===btn));$$('.auth-form').forEach(x=>x.classList.remove('active-form'));$(`#${btn.dataset.authTab}Form`).classList.add('active-form')});
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter,set=Object.fromEntries(new FormData(e.target));setBusy(btn,true);const {error}=await supabase.auth.signInWithPassword({email:set.email,password:set.password});setBusy(btn,false);if(error)toast(error.message,'error')});
$('#signupForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter,set=Object.fromEntries(new FormData(e.target));setBusy(btn,true);const {data,error}=await supabase.auth.signUp({email:set.email,password:set.password,options:{data:{full_name:set.full_name},emailRedirectTo:location.origin+location.pathname}});setBusy(btn,false);if(error)return toast(error.message,'error');toast(data.session?'Conta criada e autenticada.':'Conta criada. Confirme seu e-mail antes de entrar.');if(!data.session){$$('[data-auth-tab="login"]')[0].click()}});
$('#forgotPasswordBtn').onclick=()=>openModal(`<h3>Recuperar senha</h3><form id="resetRequestForm" class="form-stack"><label>E-mail<input name="email" type="email" required></label><div class="modal-actions"><button type="button" class="btn ghost" onclick="closeModal()">Cancelar</button><button class="btn primary">Enviar link</button></div></form>`);
function openRecoveryModal(){openModal(`<h3>Definir nova senha</h3><form id="recoveryForm" class="form-stack"><label>Nova senha<input name="password" type="password" minlength="8" required></label><label>Confirmar senha<input name="confirm" type="password" minlength="8" required></label><div class="modal-actions"><button class="btn primary">Atualizar senha</button></div></form>`)}

document.addEventListener('submit',async e=>{
  if(e.target.id==='resetRequestForm'){e.preventDefault();const btn=e.submitter,{email}=Object.fromEntries(new FormData(e.target));setBusy(btn,true);const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});setBusy(btn,false);if(error)return toast(error.message,'error');closeModal();toast('Link de recuperação enviado.');}
  if(e.target.id==='recoveryForm'){e.preventDefault();const btn=e.submitter,d=Object.fromEntries(new FormData(e.target));if(d.password!==d.confirm)return toast('As senhas não coincidem.','error');setBusy(btn,true);const {error}=await supabase.auth.updateUser({password:d.password});setBusy(btn,false);if(error)return toast(error.message,'error');closeModal();toast('Senha atualizada.');}
});

$('#onboardingForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter,d=Object.fromEntries(new FormData(e.target));setBusy(btn,true);
  try{const {data:c,error:ce}=await supabase.from('companies').insert({name:d.name,cnpj:d.cnpj||null,phone:d.phone||null,address:d.address||null,owner_user_id:user.id}).select().single();if(ce)throw ce;
    const {error:me}=await supabase.from('company_members').insert({company_id:c.id,user_id:user.id,role:'owner',full_name:user.user_metadata?.full_name||user.email});if(me)throw me;toast('Empresa criada com sucesso.');await routeAfterAuth();
  }catch(err){toast(err.message,'error')}finally{setBusy(btn,false)}
});
$('#onboardingLogout').onclick=()=>supabase.auth.signOut();$('#logoutBtn').onclick=()=>supabase.auth.signOut();

function applyIdentity(){
  $('#sidebarCompanyName').textContent=company.name;$('#userName').textContent=membership.full_name||user.user_metadata?.full_name||user.email;$('#userRole').textContent=roleLabel(membership.role);$('#userAvatar').textContent=initials($('#userName').textContent);
  renderLogo();
  $('#newEmployeeBtn').style.display=canManageEmployees()?'':'none';$('#inviteUserBtn').style.display=membership.role==='owner'?'':'none';
}
function renderLogo(){const targets=[$('#companyLogoMini'),$('#companyLogoPreview')];if(company.logo_path){const {data}=supabase.storage.from('company-logos').getPublicUrl(company.logo_path);targets.forEach(t=>t.innerHTML=`<img src="${esc(data.publicUrl)}" alt="Logo">`)}else targets.forEach(t=>{t.innerHTML='';t.textContent=initials(company.name)})}

async function loadAll(){await Promise.all([loadEmployeesAndEntries(),loadMembers()]);renderAll()}
async function loadEmployeesAndEntries(){
  const [{data:e,error:ee},{data:t,error:te}]=await Promise.all([
    supabase.from('employees').select('*').eq('company_id',company.id).order('full_name'),
    supabase.from('time_entries').select('*').eq('company_id',company.id).order('created_at',{ascending:false})
  ]);if(ee)throw ee;if(te)throw te;entries=t||[];employees=(e||[]).map(emp=>({...emp,balance_minutes:entries.filter(x=>x.employee_id===emp.id).reduce((sum,x)=>sum+(x.entry_type==='credit'?x.minutes:-x.minutes),0)}));
}
async function loadMembers(){const {data,error}=await supabase.from('company_members').select('*').eq('company_id',company.id).order('created_at');if(error)throw error;members=data||[]}
function renderAll(){renderDashboard();renderEmployees();renderReports();renderUsers();fillCompany()}
function renderDashboard(){const active=employees.filter(e=>e.active),pos=active.filter(e=>e.balance_minutes>0).reduce((s,e)=>s+e.balance_minutes,0),neg=active.filter(e=>e.balance_minutes<0).reduce((s,e)=>s+e.balance_minutes,0);$('#kpiEmployees').textContent=active.length;$('#kpiPositive').textContent=fmt(pos);$('#kpiNegative').textContent=fmt(neg);$('#kpiNet').textContent=fmt(pos+neg);
  $('#featuredEmployees').innerHTML=active.slice().sort((a,b)=>Math.abs(b.balance_minutes)-Math.abs(a.balance_minutes)).slice(0,5).map(e=>`<div class="employee-row"><div><b>${esc(e.full_name)}</b><small>${esc(e.role_title||'Sem cargo')} • ${esc(e.department||'Sem setor')}</small></div><div class="balance ${bclass(e.balance_minutes)}">${fmt(e.balance_minutes)}</div></div>`).join('')||'<div class="muted">Cadastre o primeiro funcionário.</div>';
  $('#activityList').innerHTML=entries.slice(0,6).map(x=>{const emp=employees.find(e=>e.id===x.employee_id);return `<div class="activity-row"><div class="activity-icon">${x.entry_type==='credit'?'+':'−'}</div><div class="activity-main"><b>${esc(emp?.full_name||'Funcionário')}</b><small>${esc(x.reason)} • ${new Date(x.occurred_on+'T12:00:00').toLocaleDateString('pt-BR')}</small></div><div class="balance ${x.entry_type==='credit'?'good':'bad'}">${x.entry_type==='credit'?'+':'-'}${fmt(x.minutes).replace(/[+-]/,'')}</div></div>`}).join('')||'<div class="muted">Nenhum lançamento realizado.</div>'}
function renderEmployees(){const q=$('#searchEmployee').value.toLowerCase(),bf=$('#filterBalance').value,sf=$('#filterStatus').value;let list=employees.filter(e=>`${e.full_name} ${e.registration||''} ${e.role_title||''} ${e.department||''}`.toLowerCase().includes(q));if(sf!=='all')list=list.filter(e=>sf==='active'?e.active:!e.active);if(bf!=='all')list=list.filter(e=>bf==='positive'?e.balance_minutes>0:bf==='negative'?e.balance_minutes<0:e.balance_minutes===0);
  $('#employeeGrid').innerHTML=list.map(e=>`<article class="employee-card ${e.active?'':'inactive'}"><div class="status-dot"></div><div class="employee-top"><div class="emp-avatar">${initials(e.full_name)}</div><div><h4>${esc(e.full_name)}</h4><p>Matrícula ${esc(e.registration||'-')} • ${esc(e.role_title||'Sem cargo')}</p><p>${esc(e.department||'Sem setor')}</p></div></div><div class="employee-balance ${bclass(e.balance_minutes)}">${fmt(e.balance_minutes)}</div><div class="employee-label">${e.balance_minutes>0?'Crédito do funcionário':e.balance_minutes<0?'Horas a compensar':'Saldo zerado'}</div><div class="employee-actions">${canManageTime()&&e.active?`<button class="btn primary" onclick="openEntry('${e.id}','credit')">+ Adicionar</button><button class="btn ghost" onclick="openEntry('${e.id}','debit')">− Descontar</button>`:''}<button class="btn ghost" onclick="openHistory('${e.id}')">Histórico</button><button class="btn ghost" onclick="sendEmployeeWhatsApp('${e.id}')">WhatsApp</button>${canManageEmployees()?`<button class="btn ghost" onclick="openEditEmployee('${e.id}')">Editar</button><button class="btn ${e.active?'danger':'ghost'}" onclick="toggleEmployee('${e.id}')">${e.active?'Inativar':'Reativar'}</button>`:''}</div></article>`).join('')||'<div class="panel muted">Nenhum funcionário encontrado.</div>'}
$('#searchEmployee').oninput=renderEmployees;$('#filterBalance').onchange=renderEmployees;$('#filterStatus').onchange=renderEmployees;

$('#newEmployeeBtn').onclick=()=>openEmployeeModal();
function openEmployeeModal(emp=null){openModal(`<h3>${emp?'Editar funcionário':'Novo funcionário'}</h3><form id="employeeForm" class="form-grid"><input type="hidden" name="id" value="${emp?.id||''}"><label>Nome completo<input name="full_name" value="${esc(emp?.full_name||'')}" required></label><label>Matrícula<input name="registration" value="${esc(emp?.registration||'')}" required></label><label>Cargo<input name="role_title" value="${esc(emp?.role_title||'')}"></label><label>Setor<input name="department" value="${esc(emp?.department||'')}"></label><label>WhatsApp<input name="phone" value="${esc(emp?.phone||'')}"></label><label>E-mail<input name="email" type="email" value="${esc(emp?.email||'')}"></label><label>Data de admissão<input name="admission_date" type="date" value="${emp?.admission_date||''}"></label>${emp?'':`<label>Saldo inicial (horas)<input name="initial_hours" type="number" min="0" value="0"></label><label>Tipo do saldo inicial<select name="initial_type"><option value="credit">Positivo</option><option value="debit">Negativo</option></select></label>`}<div class="modal-actions full"><button type="button" class="btn ghost" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar</button></div></form>`)}
window.openEditEmployee=id=>openEmployeeModal(employees.find(e=>e.id===id));
document.addEventListener('submit',async e=>{if(e.target.id!=='employeeForm')return;e.preventDefault();const btn=e.submitter,d=Object.fromEntries(new FormData(e.target));setBusy(btn,true);try{const payload={company_id:company.id,full_name:d.full_name,registration:d.registration,role_title:d.role_title||null,department:d.department||null,phone:d.phone||null,email:d.email||null,admission_date:d.admission_date||null};let empId=d.id;if(empId){const {error}=await supabase.from('employees').update(payload).eq('id',empId);if(error)throw error}else{const {data:created,error}=await supabase.from('employees').insert(payload).select().single();if(error)throw error;empId=created.id;const h=Number(d.initial_hours||0);if(h>0){const {error:ie}=await supabase.from('time_entries').insert({company_id:company.id,employee_id:empId,entry_type:d.initial_type,minutes:Math.round(h*60),occurred_on:new Date().toISOString().slice(0,10),reason:'Saldo inicial',notes:'Saldo cadastrado na inclusão do funcionário',created_by:user.id});if(ie)throw ie}}closeModal();await loadAll();toast('Funcionário salvo.')}catch(err){toast(err.message,'error')}finally{setBusy(btn,false)}});
window.toggleEmployee=async id=>{const e=employees.find(x=>x.id===id);if(!confirm(`${e.active?'Inativar':'Reativar'} ${e.full_name}?`))return;const {error}=await supabase.from('employees').update({active:!e.active}).eq('id',id);if(error)return toast(error.message,'error');await loadAll();toast('Situação atualizada.')};
window.openEntry=(id,type)=>{const e=employees.find(x=>x.id===id);openModal(`<h3>${type==='credit'?'Adicionar horas':'Descontar horas'} — ${esc(e.full_name)}</h3><form id="entryForm" class="form-grid"><input type="hidden" name="employee_id" value="${id}"><input type="hidden" name="entry_type" value="${type}"><label>Horas<input name="hours" type="number" min="0" value="1"></label><label>Minutos<input name="minutes" type="number" min="0" max="59" value="0"></label><label>Data<input name="occurred_on" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Motivo<input name="reason" value="${type==='credit'?'Hora extra':'Compensação'}" required></label><label class="full">Observação<textarea name="notes" rows="3"></textarea></label><div class="modal-actions full"><button type="button" class="btn ghost" onclick="closeModal()">Cancelar</button><button class="btn primary">Confirmar lançamento</button></div></form>`)};
document.addEventListener('submit',async e=>{if(e.target.id!=='entryForm')return;e.preventDefault();const btn=e.submitter,d=Object.fromEntries(new FormData(e.target)),mins=Number(d.hours||0)*60+Number(d.minutes||0);if(mins<=0)return toast('Informe horas ou minutos.','error');setBusy(btn,true);const {error}=await supabase.from('time_entries').insert({company_id:company.id,employee_id:d.employee_id,entry_type:d.entry_type,minutes:mins,occurred_on:d.occurred_on,reason:d.reason,notes:d.notes||null,created_by:user.id});setBusy(btn,false);if(error)return toast(error.message,'error');closeModal();await loadAll();toast('Lançamento registrado.')});
window.openHistory=id=>{const emp=employees.find(e=>e.id===id),hist=entries.filter(x=>x.employee_id===id);openModal(`<h3>Histórico — ${esc(emp.full_name)}</h3><div class="balance ${bclass(emp.balance_minutes)}" style="font-size:25px;margin-bottom:15px">${fmt(emp.balance_minutes)}</div><div class="history-list">${hist.map(x=>`<div class="history-item"><b class="${x.entry_type==='credit'?'good':'bad'}">${x.entry_type==='credit'?'+':'-'}${fmt(x.minutes).replace(/[+-]/,'')} • ${esc(x.reason)}</b><small>${new Date(x.occurred_on+'T12:00:00').toLocaleDateString('pt-BR')} • ${esc(x.notes||'Sem observação')}</small></div>`).join('')||'<div class="muted">Sem lançamentos.</div>'}</div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Fechar</button></div>`)};
window.sendEmployeeWhatsApp=id=>{const e=employees.find(x=>x.id===id),phone=(e.phone||'').replace(/\D/g,''),msg=`Olá, ${e.full_name}. Seu saldo atual no banco de horas da ${company.name} é ${fmt(e.balance_minutes)}. Atualizado em ${new Date().toLocaleDateString('pt-BR')}.`;if(!phone)return toast('Cadastre o WhatsApp do funcionário.','error');window.open(`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`,'_blank')};
$('#sendAllBtn').onclick=()=>{const phone=(company.phone||'').replace(/\D/g,'');if(!phone)return toast('Cadastre o WhatsApp da empresa.','error');const lines=employees.filter(e=>e.active).map(e=>`• ${e.full_name}: ${fmt(e.balance_minutes)}`).join('\n');window.open(`https://wa.me/${phone}?text=${encodeURIComponent(`Resumo do banco de horas — ${company.name}\n\n${lines}\n\nAtualizado em ${new Date().toLocaleDateString('pt-BR')}.`)}`,'_blank')};

function renderReports(){const sectors=[...new Set(employees.map(e=>e.department).filter(Boolean))].sort(),old=$('#reportSector').value;$('#reportSector').innerHTML='<option value="all">Todos</option>'+sectors.map(s=>`<option>${esc(s)}</option>`).join('');if(sectors.includes(old))$('#reportSector').value=old;updateReport()}
function updateReport(){const start=$('#reportStart').value,end=$('#reportEnd').value,sector=$('#reportSector').value,bf=$('#reportBalance').value;let list=employees.filter(e=>e.active);if(sector!=='all')list=list.filter(e=>e.department===sector);if(bf!=='all')list=list.filter(e=>bf==='positive'?e.balance_minutes>0:bf==='negative'?e.balance_minutes<0:e.balance_minutes===0);const periodEntries=entries.filter(x=>(!start||x.occurred_on>=start)&&(!end||x.occurred_on<=end));const credit=periodEntries.filter(x=>x.entry_type==='credit').reduce((s,x)=>s+x.minutes,0),debit=periodEntries.filter(x=>x.entry_type==='debit').reduce((s,x)=>s+x.minutes,0);$('#reportSummary').innerHTML=`<div class="mini-kpi"><span>Créditos no período</span><strong class="good">${fmt(credit)}</strong></div><div class="mini-kpi"><span>Débitos no período</span><strong class="bad">-${fmt(debit).replace(/[+-]/,'')}</strong></div><div class="mini-kpi"><span>Movimento líquido</span><strong class="${bclass(credit-debit)}">${fmt(credit-debit)}</strong></div>`;$('#reportTableWrap').innerHTML=`<table class="report-table"><thead><tr><th>Funcionário</th><th>Matrícula</th><th>Setor</th><th>Créditos período</th><th>Débitos período</th><th>Saldo atual</th></tr></thead><tbody>${list.map(e=>{const pe=periodEntries.filter(x=>x.employee_id===e.id),pc=pe.filter(x=>x.entry_type==='credit').reduce((s,x)=>s+x.minutes,0),pd=pe.filter(x=>x.entry_type==='debit').reduce((s,x)=>s+x.minutes,0);return `<tr><td>${esc(e.full_name)}</td><td>${esc(e.registration)}</td><td>${esc(e.department||'-')}</td><td class="good">${fmt(pc)}</td><td class="bad">-${fmt(pd).replace(/[+-]/,'')}</td><td class="${bclass(e.balance_minutes)}">${fmt(e.balance_minutes)}</td></tr>`}).join('')}</tbody></table>`}
['reportStart','reportEnd','reportSector','reportBalance'].forEach(id=>$(`#${id}`).onchange=updateReport);$('#printReportBtn').onclick=()=>window.print();

function renderUsers(){$('#usersList').innerHTML=members.map(m=>`<div class="user-row"><div><b>${esc(m.full_name||'Usuário')}</b><small>${m.user_id===user.id?'Seu acesso':'Usuário convidado'}</small></div><span class="role-pill">${roleLabel(m.role)}</span></div>`).join('')||'<div class="muted">Nenhum usuário.</div>'}
$('#inviteUserBtn').onclick=()=>openModal(`<h3>Convidar usuário</h3><form id="inviteForm" class="form-grid"><label>Nome<input name="full_name" required></label><label>E-mail<input name="email" type="email" required></label><label>Perfil<select name="role"><option value="operator">Responsável pelas horas</option><option value="admin">Administrador</option></select></label><div class="modal-actions full"><button type="button" class="btn ghost" onclick="closeModal()">Cancelar</button><button class="btn primary">Enviar convite</button></div></form>`);
document.addEventListener('submit',async e=>{if(e.target.id!=='inviteForm')return;e.preventDefault();const btn=e.submitter,d=Object.fromEntries(new FormData(e.target));setBusy(btn,true);const {data,error}=await supabase.functions.invoke('invite-company-user',{body:{companyId:company.id,email:d.email,fullName:d.full_name,role:d.role}});setBusy(btn,false);if(error||data?.error)return toast(data?.error||error.message,'error');closeModal();await loadMembers();renderUsers();toast('Convite enviado por e-mail.')});

function fillCompany(){$('#companyName').value=company.name||'';$('#companyCnpj').value=company.cnpj||'';$('#companyPhone').value=company.phone||'';$('#companyAddress').value=company.address||'';$('#companyForm').querySelector('button').disabled=!canManageCompany();$('#companyLogoInput').disabled=!canManageCompany()}
$('#companyForm').addEventListener('submit',async e=>{e.preventDefault();if(!canManageCompany())return;const btn=e.submitter;setBusy(btn,true);const payload={name:$('#companyName').value,cnpj:$('#companyCnpj').value||null,phone:$('#companyPhone').value||null,address:$('#companyAddress').value||null};const {data,error}=await supabase.from('companies').update(payload).eq('id',company.id).select().single();setBusy(btn,false);if(error)return toast(error.message,'error');company={...company,...data};applyIdentity();toast('Empresa atualizada.')});
$('#companyLogoInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file||!canManageCompany())return;if(file.size>2*1024*1024)return toast('A logo deve ter no máximo 2 MB.','error');const ext=file.name.split('.').pop().toLowerCase(),path=`${company.id}/logo.${ext}`;toast('Enviando logo...');const {error}=await supabase.storage.from('company-logos').upload(path,file,{upsert:true,contentType:file.type});if(error)return toast(error.message,'error');const {data,error:ue}=await supabase.from('companies').update({logo_path:path}).eq('id',company.id).select().single();if(ue)return toast(ue.message,'error');company={...company,...data};renderLogo();toast('Logo atualizada.')});

$$('.nav-item').forEach(btn=>btn.onclick=()=>goPage(btn.dataset.page));$$('[data-goto]').forEach(btn=>btn.onclick=()=>goPage(btn.dataset.goto));
function goPage(id){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$$('.page').forEach(x=>x.classList.toggle('active-page',x.id===id));$('#pageTitle').textContent=({dashboard:'Visão geral',employees:'Funcionários',reports:'Relatórios',users:'Usuários',company:'Empresa'})[id];if(id==='reports')renderReports()}
